name: Webapp-Watcher
markdown: redcarpet
pygments: true
repository: 'https://github.com/iorga-group/webapp-watcher'
baseurl: ''

redcarpet:
  extensions: ["tables"]
lessc: 'node_modules/less/bin/lessc'

exclude: ['Rakefile', 'README.md', 'package.json', 'node_modules']
