# thanks to http://blog.nitrous.io/2013/08/30/using-jekyll-plugins-on-github-pages.html and https://github.com/jekyll/jekyll/blob/master/Rakefile

require "rubygems"
require "tmpdir"

require "bundler/setup"
require "jekyll"


# Change your GitHub reponame
GITHUB_REPONAME = "iorga-group/webapp-watcher"

namespace :site do
  desc "Generate blog files"
  task :generate do
    sh "jekyll build"
  end

  desc "Generate and publish blog to gh-pages"
  task :publish => [:generate] do
    Dir.mktmpdir do |tmp|
      cp_r "_site/.", tmp

      pwd = Dir.pwd
      Dir.chdir tmp

      sh "git init"
      sh "git add ."
      message = "Site updated at #{Time.now.utc}"
      sh "git commit -m #{message.inspect}"
      sh "git remote add origin git@github.com:#{GITHUB_REPONAME}.git"
      sh "git push origin master:refs/heads/gh-pages --force"

      Dir.chdir pwd
    end

    puts 'Done.'
  end
end
