# thanks to http://blog.nitrous.io/2013/08/30/using-jekyll-plugins-on-github-pages.html and https://github.com/jekyll/jekyll/blob/master/Rakefile

require "rubygems"
require "tmpdir"

require "bundler/setup"
require "jekyll"


# Change your GitHub reponame
GITHUB_REPONAME = "iorga-group/webapp-watcher"

namespace :site do
  desc "Generate blog files"
  task :generate do
    sh "jekyll build"
  end

  desc "Generate and publish blog to gh-pages"
  task :publish => [:generate] do
    sha = `git log`.match(/[a-z0-9]{40}/)[0]
    Dir.mktmpdir do |tmp|
      cp_r "_site/.", tmp
      Dir.mktmpdir do |tmp2|
        Dir.chdir(tmp2) do
          sh "git clone git@github.com:#{GITHUB_REPONAME} gh-pages"
          Dir.chdir('gh-pages') do
            sh "git checkout gh-pages"
            sh "git pull origin gh-pages"
            sh "rm -rf *"
            cp_r "#{tmp}/.", "./"
            sh "git add ."
            sh "git commit -m 'Updating to #{sha} at #{Time.now.utc}'"
            sh "git push origin gh-pages"
          end
        end
      end
    end

    puts 'Done.'
  end
end
